name: Build KeepInventoryCost

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
          cache: maven

      - name: Build with Maven
        run: mvn -DskipTests package
        working-directory: KeepInventoryCostPlugin-main

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: KeepInventoryCost
          path: KeepInventoryCostPlugin-main/target/*.jar
